title = "absolutely nothing here"
author = "prasad chalasani"
theme = "hugo-theme-bleak"

[params]
  # Warning Keys are case sensitives
  Subtitle = "ungeneric generics"
  description = "Everything is awesome !"
  cover = "/images/cover.jpg"

  # Google analytics
#  googleAnalyticsUserID = "UA-xxxxxxxx-x"
#  domainVerification = "xxxxxxxxxxxxxxxxxxxxx"
  disqus = "pchalasani"

  [params.author]
    firstName = "Prasad"
    lastName = "Chalasani"
    gender = "male"
    userName = "pchalasani"
    image = "https://s.gravatar.com/avatar/899234e4fe0c900678e00b6b42908342?s=80"
    website = "http://www.foo.com"
    twitter = "pchalasani"
    github = "pchalasani"
#    facebook = "xxxxxxxxx"
#    linkedin = "xxxxxxxxx"
#    gplus = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    gravatarHash = "899234e4fe0c900678e00b6b42908342"
