baseurl = "/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Absolutely about nothing"
theme = "slim"

# enableRobotsTXT = true

# googleAnalytics = ""

# disqusShortname = ""

[params]
  Subtitle = "Your site's subtitle/tagline"
  GithubID = "pchalasani"
  TwitterID = "pchalasani"
#  AnalyticsID = "Your Google Analytics tracking code"
  DisqusShortname = "pchalasani"
  Summary = true  # takes true or false
  Content = false  # takes true or false
                # if both are set to true, summary is shown.
                  # FooterMsg = "Copyright Me 2016. Powered by Hugo."
