---
pages:
- post/post-from-forestry-.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: subtitle
  label: Subtitle
  type: text
  hidden: false
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- type: text
- type: textarea
- type: textarea
  config:
    wysiwyg: true
  label: text
  name: text
- type: textarea
